[versions]
agp = "8.3.1"
kotlin = "1.9.0"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
multidex = "2.0.1"
slf4j = "2.0.12"
logback = "3.0.0"
conscrypt = "2.5.2"
okhttp = "4.12.0"
lib-phone-number-info = "c77bdd2b69"
commons-csv = "1.10.0"
recyclerview = "1.3.2"
recyclerview-selection = "1.1.0"
paging-runtime = "3.2.1"
google-material = "1.11.0"
preference = "1.2.1"
work-runtime = "2.9.0"
eventbus = "3.3.1"
sqlite = "2.0.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "work-runtime" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-recyclerview-selection = { group = "androidx.recyclerview", name = "recyclerview-selection", version.ref = "recyclerview-selection" }
androidx-paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging-runtime" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }

google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logback = { group = "com.github.tony19", name = "logback-android", version.ref = "logback" }
conscrypt = { group = "org.conscrypt", name = "conscrypt-android", version.ref = "conscrypt" }
commons-csv = { group = "org.apache.commons", name = "commons-csv", version.ref = "commons-csv" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
lib-phone-number-info = { group = "com.gitlab.xynngh", name = "LibPhoneNumberInfo", version.ref = "lib-phone-number-info" }

sqlite-driver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqlite" }
sqlite-coroutines = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqlite" }

eventbus = { group = "org.greenrobot", name = "eventbus", version.ref = "eventbus" }
eventbus-annotation-processor = { group = "org.greenrobot", name = "eventbus-annotation-processor", version.ref = "eventbus" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
sqlite = { id = "app.cash.sqldelight", version.ref = "sqlite" }

